version: '3.8'

services:

  db:
    image: postgres:alpine
    container_name: 'quicksell_db'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: 'env'
    restart: always

  app:
    build: .
    image: 'quicksell'
    container_name: 'quicksell_app'
    command: sh -c "postfix start; python manage.py runserver 0.0.0.0:8000"
    ports:
      - 7777:8000
    volumes:
      - ./quicksell:/opt/app
    env_file: 'env'
    restart: always
    depends_on:
      - db

volumes:
  db_data: {}
